### ISSUE TITLE
[Winter 1.2] SQLerror : dimsog_slider_slides

### ISSUE THREAD

**Issue by m-paniez9292** [dimsog/wn-slider-plugin#1]
Hi,

I'm using Wintercms 1.2 with php 8.1.

After a fresh install, I put your plugin with a `composer require dimsog/wn-slider-plugin`.

Just after, I try to go to the backend menu and I have this error : `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxxx.dimsog_slider_slides' doesn't exist (SQL: select count(*) as aggregate from `dimsog_slider_slides`)`

Thanks

**Comment by dimsog** [comment]
Hi!
Try this: 
`
php artisan plugin:refresh Dimsog.Slider
`

**Comment by m-paniez9292** [comment]
Re,

It works.
Thanks
