### ISSUE TITLE
[Winter 1.2] Display problem

### ISSUE THREAD

**Issue by m-paniez9292** [dimsog/wn-slider-plugin#2]
Hi,

I have some trouble with the display : are there some depends ?

Thanks

**Comment by dimsog** [comment]
{% styles %}

and 

{% scripts %}

are on the layout?

Please give me a screenshot or demo

**Comment by m-paniez9292** [comment]
Re,
![Capture d’écran de 2022-09-23 10-05-42](https://user-images.githubusercontent.com/17120690/191917638-a4924ebe-80a3-4f24-a2b5-a585eefbeea5.png)

I give you the part of the slideshow. I confirm I put styles and scripts on the layout.

Thanks

**Comment by dimsog** [comment]
See demo:
https://demo.dimsog.ru

Are these scripts on the page and working?
https://site.com/plugins/dimsog/slider/assets/swiper/swiper.min.css
https://site.com/plugins/dimsog/slider/assets/style.css

https://site.com/plugins/dimsog/slider/assets/swiper/swiper.min.js
https://site.com/plugins/dimsog/slider/assets/script.js

**Comment by m-paniez9292** [comment]
Re,

I have js files, but I don't have css files.

Thanks

**Comment by elrefaie80** [comment]
please the demo is not working , it is showing only one photo for me and the buttons are not switching , your support is appreciated
